---
- hosts: all
  become: yes
  tasks:
  - name: Install Apache
    yum: pkg=httpd state=latest

  - name: Enable Apache on System Boot
    service: name=httpd enabled=yes
  - name: start the service
    service: name=httpd status=restarted
  - name: iptables check
    iptables:
      chain: INPUT
      in_interface: eth0
      protocol: tcp
      match: tcp
      destination_port: 80
      ctstate: NEW
      jump: ACCEPT
